version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=sreality_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db


  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sreality_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5555:5432"